// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dtos "lms-main-service/internal/dtos"

	mock "github.com/stretchr/testify/mock"
)

// ChapterService is an autogenerated mock type for the ChapterService type
type ChapterService struct {
	mock.Mock
}

// CreateChapter provides a mock function with given fields: chapter
func (_m *ChapterService) CreateChapter(chapter dtos.ChapterDTO) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.ChapterDTO) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChapter provides a mock function with given fields: id
func (_m *ChapterService) DeleteChapter(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChapter provides a mock function with given fields: id
func (_m *ChapterService) GetChapter(id uint) (dtos.ChapterDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChapter")
	}

	var r0 dtos.ChapterDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dtos.ChapterDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dtos.ChapterDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dtos.ChapterDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChaptersByCourseID provides a mock function with given fields: courseID
func (_m *ChapterService) GetChaptersByCourseID(courseID uint) ([]dtos.ChapterDTO, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetChaptersByCourseID")
	}

	var r0 []dtos.ChapterDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dtos.ChapterDTO, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dtos.ChapterDTO); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.ChapterDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChapter provides a mock function with given fields: updChapter
func (_m *ChapterService) UpdateChapter(updChapter dtos.ChapterDTO) error {
	ret := _m.Called(updChapter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.ChapterDTO) error); ok {
		r0 = rf(updChapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterService creates a new instance of ChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterService {
	mock := &ChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
