// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lms-main-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ChapterRepository is an autogenerated mock type for the ChapterRepository type
type ChapterRepository struct {
	mock.Mock
}

// CreateChapter provides a mock function with given fields: chapter
func (_m *ChapterRepository) CreateChapter(chapter *models.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChapter provides a mock function with given fields: id
func (_m *ChapterRepository) DeleteChapter(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBy provides a mock function with given fields: query, args
func (_m *ChapterRepository) GetBy(query string, args ...interface{}) (*models.Chapter, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBy")
	}

	var r0 *models.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*models.Chapter, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *models.Chapter); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChapter provides a mock function with given fields: id
func (_m *ChapterRepository) GetChapter(id uint) (*models.Chapter, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChapter")
	}

	var r0 *models.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Chapter, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Chapter); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChaptersByCourseID provides a mock function with given fields: courseID
func (_m *ChapterRepository) GetChaptersByCourseID(courseID uint) (*[]models.Chapter, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetChaptersByCourseID")
	}

	var r0 *[]models.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*[]models.Chapter, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) *[]models.Chapter); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChapter provides a mock function with given fields: updChapter
func (_m *ChapterRepository) UpdateChapter(updChapter *models.Chapter) error {
	ret := _m.Called(updChapter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Chapter) error); ok {
		r0 = rf(updChapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterRepository creates a new instance of ChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterRepository {
	mock := &ChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
