// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dtos "lms-main-service/internal/dtos"

	mock "github.com/stretchr/testify/mock"
)

// CourseService is an autogenerated mock type for the CourseService type
type CourseService struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: course
func (_m *CourseService) CreateCourse(course dtos.CourseDTO) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.CourseDTO) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCourse provides a mock function with given fields: id
func (_m *CourseService) DeleteCourse(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourses provides a mock function with no fields
func (_m *CourseService) GetAllCourses() ([]dtos.CourseDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 []dtos.CourseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dtos.CourseDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dtos.CourseDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.CourseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: id
func (_m *CourseService) GetCourse(id uint) (dtos.CourseDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 dtos.CourseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dtos.CourseDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dtos.CourseDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dtos.CourseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourse provides a mock function with given fields: updCourse
func (_m *CourseService) UpdateCourse(updCourse dtos.CourseDTO) error {
	ret := _m.Called(updCourse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.CourseDTO) error); ok {
		r0 = rf(updCourse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseService creates a new instance of CourseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseService {
	mock := &CourseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
