// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lms-main-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: course
func (_m *CourseRepository) CreateCourse(course *models.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCourse provides a mock function with given fields: id
func (_m *CourseRepository) DeleteCourse(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourses provides a mock function with no fields
func (_m *CourseRepository) GetAllCourses() (*[]models.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 *[]models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]models.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]models.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBy provides a mock function with given fields: query, args
func (_m *CourseRepository) GetBy(query string, args ...interface{}) (*models.Course, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBy")
	}

	var r0 *models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*models.Course, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *models.Course); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: id
func (_m *CourseRepository) GetCourse(id uint) (*models.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Course); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourse provides a mock function with given fields: updCourse
func (_m *CourseRepository) UpdateCourse(updCourse *models.Course) error {
	ret := _m.Called(updCourse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Course) error); ok {
		r0 = rf(updCourse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
