// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dtos "lms-main-service/internal/dtos"

	mock "github.com/stretchr/testify/mock"
)

// LessonService is an autogenerated mock type for the LessonService type
type LessonService struct {
	mock.Mock
}

// CreateLesson provides a mock function with given fields: lesson
func (_m *LessonService) CreateLesson(lesson dtos.LessonDTO) error {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for CreateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.LessonDTO) error); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLesson provides a mock function with given fields: id
func (_m *LessonService) DeleteLesson(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLesson provides a mock function with given fields: id
func (_m *LessonService) GetLesson(id uint) (dtos.LessonDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLesson")
	}

	var r0 dtos.LessonDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dtos.LessonDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dtos.LessonDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dtos.LessonDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonsByChapterID provides a mock function with given fields: chapterID
func (_m *LessonService) GetLessonsByChapterID(chapterID uint) ([]dtos.LessonDTO, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsByChapterID")
	}

	var r0 []dtos.LessonDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dtos.LessonDTO, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dtos.LessonDTO); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.LessonDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLesson provides a mock function with given fields: updLesson
func (_m *LessonService) UpdateLesson(updLesson dtos.LessonDTO) error {
	ret := _m.Called(updLesson)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dtos.LessonDTO) error); ok {
		r0 = rf(updLesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLessonService creates a new instance of LessonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonService {
	mock := &LessonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
