// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lms-main-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// LessonRepository is an autogenerated mock type for the LessonRepository type
type LessonRepository struct {
	mock.Mock
}

// CreateLesson provides a mock function with given fields: lesson
func (_m *LessonRepository) CreateLesson(lesson *models.Lesson) error {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for CreateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Lesson) error); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLesson provides a mock function with given fields: id
func (_m *LessonRepository) DeleteLesson(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBy provides a mock function with given fields: query, args
func (_m *LessonRepository) GetBy(query string, args ...interface{}) (*models.Lesson, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBy")
	}

	var r0 *models.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*models.Lesson, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *models.Lesson); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLesson provides a mock function with given fields: id
func (_m *LessonRepository) GetLesson(id uint) (*models.Lesson, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLesson")
	}

	var r0 *models.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Lesson, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Lesson); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonsByChapterID provides a mock function with given fields: chapterID
func (_m *LessonRepository) GetLessonsByChapterID(chapterID uint) (*[]models.Lesson, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsByChapterID")
	}

	var r0 *[]models.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*[]models.Lesson, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) *[]models.Lesson); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLesson provides a mock function with given fields: updLesson
func (_m *LessonRepository) UpdateLesson(updLesson *models.Lesson) error {
	ret := _m.Called(updLesson)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Lesson) error); ok {
		r0 = rf(updLesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLessonRepository creates a new instance of LessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonRepository {
	mock := &LessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
